import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Stitch "Vigilance Modern" design system
        background: "#0e1323",
        "surface-dim": "#0e1323",
        surface: "#0e1323",
        "surface-container-lowest": "#080d1d",
        "surface-container-low": "#161b2b",
        "surface-container": "#1a1f30",
        "surface-container-high": "#25293a",
        "surface-container-highest": "#2f3446",
        "surface-bright": "#34394a",
        "surface-variant": "#2f3446",
        "on-surface": "#dee1f9",
        "on-surface-variant": "#c7c4d7",
        "on-background": "#dee1f9",
        "inverse-surface": "#dee1f9",
        "inverse-on-surface": "#2b3041",
        outline: "#908fa0",
        "outline-variant": "#464554",
        // Primary — indigo/violet
        primary: "#c0c1ff",
        "on-primary": "#1000a9",
        "primary-container": "#8083ff",
        "on-primary-container": "#0d0096",
        "primary-fixed": "#e1e0ff",
        "primary-fixed-dim": "#c0c1ff",
        "on-primary-fixed": "#07006c",
        "on-primary-fixed-variant": "#2f2ebe",
        "inverse-primary": "#494bd6",
        "surface-tint": "#c0c1ff",
        // Secondary — teal (SAFE / Health)
        secondary: "#4fdbc8",
        "on-secondary": "#003731",
        "secondary-container": "#04b4a2",
        "on-secondary-container": "#003f38",
        "secondary-fixed": "#71f8e4",
        "secondary-fixed-dim": "#4fdbc8",
        "on-secondary-fixed": "#00201c",
        "on-secondary-fixed-variant": "#005048",
        // Tertiary — red/rose (EMERGENCY ONLY)
        tertiary: "#ffb3b6",
        "on-tertiary": "#68001a",
        "tertiary-container": "#ff5168",
        "on-tertiary-container": "#5b0015",
        "tertiary-fixed": "#ffdada",
        "tertiary-fixed-dim": "#ffb3b6",
        "on-tertiary-fixed": "#40000c",
        "on-tertiary-fixed-variant": "#920028",
        // Error
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        // Warning (amber)
        warning: "#F59E0B",
        "warning-container": "#D97706",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Manrope", "sans-serif"],
        "headline-xl": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "14px", fontWeight: "500" }],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "2rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "2xl": "48px",
        "margin-mobile": "20px",
        "margin-desktop": "48px",
        gutter: "16px",
      },
      backgroundImage: {
        "gradient-primary": "linear-gradient(135deg, #494bd6 0%, #8083ff 100%)",
        "gradient-secondary": "linear-gradient(135deg, #0EA5A4 0%, #4fdbc8 100%)",
        "gradient-safety": "linear-gradient(135deg, #2563EB 0%, #4F46E5 100%)",
        "gradient-warning": "linear-gradient(135deg, #D97706 0%, #F59E0B 100%)",
        "gradient-emergency": "linear-gradient(135deg, #DC2626 0%, #E11D48 100%)",
        "gradient-hero": "radial-gradient(ellipse 80% 60% at 50% -10%, rgba(99,102,241,0.25) 0%, transparent 70%)",
      },
      animation: {
        "pulse-glow": "pulseGlow 2s infinite alternate",
        "sos-glow": "sosGlow 1.5s infinite alternate",
        "sos-ring": "sosRing 1.5s cubic-bezier(0, 0, 0.2, 1) infinite",
        "fade-in": "fadeIn 0.4s ease-out",
        "slide-up": "slideUp 0.4s ease-out",
        "scale-in": "scaleIn 0.3s ease-out",
        float: "float 4s ease-in-out infinite",
      },
      keyframes: {
        pulseGlow: {
          "0%": { boxShadow: "0 0 10px rgba(79, 219, 200, 0.2)" },
          "100%": { boxShadow: "0 0 30px rgba(79, 219, 200, 0.6)" },
        },
        sosGlow: {
          "0%": { boxShadow: "0 0 15px rgba(225, 29, 72, 0.4)" },
          "100%": { boxShadow: "0 0 40px rgba(225, 29, 72, 0.9)" },
        },
        sosRing: {
          "75%, 100%": { transform: "scale(2)", opacity: "0" },
        },
        fadeIn: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        slideUp: {
          from: { transform: "translateY(16px)", opacity: "0" },
          to: { transform: "translateY(0)", opacity: "1" },
        },
        scaleIn: {
          from: { transform: "scale(0.95)", opacity: "0" },
          to: { transform: "scale(1)", opacity: "1" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-8px)" },
        },
      },
      backdropBlur: {
        xs: "4px",
        sm: "8px",
        DEFAULT: "16px",
        lg: "24px",
        xl: "40px",
      },
      boxShadow: {
        glass: "0 8px 32px rgba(0,0,0,0.3), inset 0 1px 0 rgba(255,255,255,0.05)",
        card: "0 4px 24px rgba(0,0,0,0.25)",
        emergency: "0 0 40px rgba(225,29,72,0.5)",
        safe: "0 0 30px rgba(79,219,200,0.3)",
        primary: "0 0 20px rgba(128,131,255,0.3)",
      },
    },
  },
  plugins: [],
};

export default config;
